ALTER TABLE "public"."products"
  ADD COLUMN IF NOT EXISTS "platform_fees" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "shipping_cost" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "marketing_cost" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "other_costs" DOUBLE PRECISION;